### ISSUE TITLE
`make run` failed

### ISSUE THREAD

**Issue by gyliu513** [crossplane/crossplane.github.io#84]
```console
root@gyliu-dev21:~/go/src/github.com/crossplane/crossplane.github.io# make run
...
There was an error while trying to write to `/srv/jekyll/Gemfile.lock`. It is likely that you need to grant write permissions for that path.
make: *** [Makefile:6: run] Error 23
```
```console
root@gyliu-dev21:~/go/src/github.com/crossplane/crossplane.github.io# ls -lrt /srv/jekyll/
total 0
```
```console
root@gyliu-dev21:~/go/src/github.com/crossplane/crossplane.github.io# ls -lrt /srv
total 0
drwxr-xr-x 2 root root 6 Jan  5 04:23 jekyll
```

**Comment by jbw976** [comment]
Hey there @gyliu513, `/srv/jekyll/...` is referring to a path inside the container that is running/building the site.  See how the Makefile bind mounts `$(PWD)` to `/srv/jekyll`: https://github.com/crossplane/crossplane.github.io/blob/master/Makefile#L9

* Is the `Gemfile.lock` file in the present directory and with OK permisions?
* is there any other helpful output in `make run` before the error message?
* do you see the same issue when running `make build` followed by `make run`?

**Comment by gyliu513** [comment]
> Is the Gemfile.lock file in the present directory and with OK permisions?

No, it does not have `w` permission.

```console
root@gyliu-dev21:~/go/src/github.com/crossplane/crossplane.github.io# ls -l Gemfile*
-rw-r--r-- 1 root root   73 Jan  5 04:21 Gemfile
-rw-r--r-- 1 root root 7104 Jan  5 04:21 Gemfile.lock
```

> is there any other helpful output in make run before the error message?

No other info, but just report this error.

> do you see the same issue when running make build followed by make run?

Yes, `make build` also have same error.

After I grant `w` permission as follows:
```console
root@gyliu-dev21:~/go/src/github.com/crossplane/crossplane.github.io# chmod a+w Gemfile.lock
```

`make run` got another error (Seems the original permission issue has been fixed)

```
Bundle complete! 1 Gemfile dependency, 90 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.9.0 | Error:  Permission denied @ dir_s_mkdir - /srv/jekyll/_site
Traceback (most recent call last):
	30: from /usr/local/bundle/bin/jekyll:29:in `<main>'
	29: from /usr/local/bundle/bin/jekyll:29:in `load'
	28: from /usr/gem/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
	27: from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	26: from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	25: from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	24: from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	23: from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	22: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
	21: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `start'
	20: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `each'
	19: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/serve.rb:93:in `block in start'
	18: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
	17: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
	16: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
	15: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:73:in `process'
	14: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:208:in `write'
	13: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:330:in `each_site_file'
	12: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:330:in `each'
	11: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:331:in `block in each_site_file'
	10: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:331:in `each'
	 9: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:332:in `block (2 levels) in each_site_file'
	 8: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:209:in `block in write'
	 7: from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/convertible.rb:226:in `write'
	 6: from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
	 5: from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
	 4: from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
	 3: from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
	 2: from /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
	 1: from /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
/usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /srv/jekyll/_site (Errno::EACCES)
make: *** [Makefile:6: run] Error 1
```
